"""initial production schema

Revision ID: 0001_production_schema
Revises:
Create Date: 2026-08-20 21:24:07.330840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_production_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('monthly_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monthly_compute_credits', sa.BigInteger(), nullable=False),
    sa.Column('max_source_minutes_per_job', sa.Integer(), nullable=False),
    sa.Column('max_clips_per_job', sa.Integer(), nullable=False),
    sa.Column('max_active_jobs', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('max_active_jobs > 0', name=op.f('ck_plans_active_jobs_positive')),
    sa.CheckConstraint('max_clips_per_job > 0', name=op.f('ck_plans_clips_positive')),
    sa.CheckConstraint('max_source_minutes_per_job > 0', name=op.f('ck_plans_source_minutes_positive')),
    sa.CheckConstraint('monthly_compute_credits >= 0', name=op.f('ck_plans_monthly_credits_nonnegative')),
    sa.CheckConstraint('monthly_price_minor >= 0', name=op.f('ck_plans_monthly_price_nonnegative')),
    sa.CheckConstraint('retention_days > 0', name=op.f('ck_plans_retention_days_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clerk_subject', sa.Text(), nullable=False),
    sa.Column('email_normalized', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status', native_enum=False), nullable=False),
    sa.Column('role', sa.Enum('user', 'support', 'admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'support', 'admin')", name=op.f('ck_users_user_role')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name=op.f('ck_users_user_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('clerk_subject', name=op.f('uq_users_clerk_subject'))
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_key', sa.Text(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'provider_event_key', name='uq_webhook_events_provider_event_key')
    )
    op.create_table('credit_wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('available', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available >= 0', name=op.f('ck_credit_wallets_available_nonnegative')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_credit_wallets_reserved_nonnegative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_wallets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_credit_wallets'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=False),
    sa.Column('provider_conversation_id', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', 'cancelled', name='payment_status', native_enum=False), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('raw_event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed', 'refunded', 'cancelled')", name=op.f('ck_payments_payment_status')),
    sa.CheckConstraint('amount_minor >= 0', name=op.f('ck_payments_amount_nonnegative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id'))
    )
    op.create_index(op.f('ix_payments_provider_conversation_id'), 'payments', ['provider_conversation_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('youtube', 'upload', name='source_type', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('youtube', 'upload')", name=op.f('ck_projects_source_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_source_fingerprint'), 'projects', ['source_fingerprint'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('signal', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_events_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_request_id'), 'risk_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default=sa.text("'iyzico'"), nullable=False),
    sa.Column('provider_subscription_ref', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'past_due', 'cancelled', 'expired', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'past_due', 'cancelled', 'expired')", name=op.f('ck_subscriptions_subscription_status')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('provider_subscription_ref', name=op.f('uq_subscriptions_provider_subscription_ref'))
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('trial_entitlements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_key_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('available', 'claimed', 'blocked', name='trial_status', native_enum=False), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('available', 'claimed', 'blocked')", name=op.f('ck_trial_entitlements_trial_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trial_entitlements_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_entitlements')),
    sa.UniqueConstraint('identity_key_hash', name='uq_trial_entitlements_identity_key_hash')
    )
    op.create_index(op.f('ix_trial_entitlements_user_id'), 'trial_entitlements', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('preview', 'full_render', 'reburn', 'batch', name='job_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'error', 'cancelled', 'review_required', name='job_status', native_enum=False), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reserved_credits', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('settled_credits', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('gpu_seconds', sa.BigInteger(), nullable=True),
    sa.Column('gpu_model', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'error', 'cancelled', 'review_required')", name=op.f('ck_jobs_job_status')),
    sa.CheckConstraint("type IN ('preview', 'full_render', 'reburn', 'batch')", name=op.f('ck_jobs_job_type')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_jobs_progress_range')),
    sa.CheckConstraint('reserved_credits >= 0', name=op.f('ck_jobs_reserved_credits_nonnegative')),
    sa.CheckConstraint('settled_credits >= 0', name=op.f('ck_jobs_settled_credits_nonnegative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('source', 'transcript', 'preview', 'short', 'thumbnail', 'debug', name='asset_kind', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('source', 'transcript', 'preview', 'short', 'thumbnail', 'debug')", name=op.f('ck_assets_asset_kind')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_assets_size_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_assets_job_id_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_assets_storage_key'))
    )
    op.create_index(op.f('ix_assets_job_id'), 'assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('grant', 'reserve', 'release', 'settle', 'refund', 'adjustment', 'expire', name='ledger_kind', native_enum=False), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('grant', 'reserve', 'release', 'settle', 'refund', 'adjustment', 'expire')", name=op.f('ck_credit_ledger_ledger_kind')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_credit_ledger_job_id_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_credit_ledger_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_ledger_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_credit_ledger_idempotency_key'))
    )
    op.create_index(op.f('ix_credit_ledger_job_id'), 'credit_ledger', ['job_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_payment_id'), 'credit_ledger', ['payment_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'error', 'cancelled', 'review_required', name='job_event_status', native_enum=False), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'error', 'cancelled', 'review_required')", name=op.f('ck_job_events_job_event_status')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_payment_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_job_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_job_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_trial_entitlements_user_id'), table_name='trial_entitlements')
    op.drop_table('trial_entitlements')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_request_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_source_fingerprint'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_conversation_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('credit_wallets')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
